[project]
name = "projtrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi[standard]>=0.116.1",
    "sqlalchemy>=2.0.43",
    "typer>=0.17.4",
]
